<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="All-tests [Firefox]"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="203.606">
  <properties />
            <testcase name="countSearchResult" time="203.606" classname="com.google.tests.N_0005_CountSearchResultTest">
                <failure type="java.lang.AssertionError"
                  message="expected [149] but found [140]"
              >
<![CDATA[java.lang.AssertionError: expected [149] but found [140]
  org.testng.Assert.fail(Assert.java:110)
  org.testng.Assert.failNotEquals(Assert.java:1577)
  org.testng.Assert.assertEqualsImpl(Assert.java:149)
  org.testng.Assert.assertEquals(Assert.java:131)
  org.testng.Assert.assertEquals(Assert.java:1418)
  org.testng.Assert.assertEquals(Assert.java:1382)
  org.testng.Assert.assertEquals(Assert.java:1428)
  com.google.actionHelpers.CountSearchResult.countAndEqualsSearchResults(CountSearchResult.java:27)
  com.google.tests.N_0005_CountSearchResultTest.countSearchResult(N_0005_CountSearchResultTest.java:17)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  java.base/java.lang.reflect.Method.invoke(Method.java:580)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
  org.testng.TestRunner.privateRun(TestRunner.java:829)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
  org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  java.base/java.lang.Thread.run(Thread.java:1583)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
